package xyz.fkstrading.shared.data.websocket.messages

import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

/**
 * Base class for all WebSocket messages from the FKS backend.
 *
 * Messages are discriminated by the "type" field in the JSON payload.
 * This enables polymorphic deserialization of different message types.
 */
@OptIn(ExperimentalSerializationApi::class)
@Serializable
@JsonClassDiscriminator("type")
sealed class WebSocketMessage {
    abstract val timestamp: String
}

/**
 * Real-time trading signal message.
 *
 * Sent when a new trading signal is generated by the backend.
 */
@Serializable
@SerialName("signal")
data class SignalMessage(
    override val timestamp: String,
    val data: SignalData,
) : WebSocketMessage()

@Serializable
data class SignalData(
    val id: String,
    val symbol: String,
    val type: String, // "BUY" or "SELL"
    val price: Double,
    val confidence: Double,
    val strategy: String? = null,
    val timeframe: String? = null,
    val indicators: Map<String, String>? = null,
)

/**
 * Real-time order update message.
 *
 * Sent when an order is created, updated, filled, or cancelled.
 */
@Serializable
@SerialName("order")
data class OrderMessage(
    override val timestamp: String,
    val data: OrderData,
) : WebSocketMessage()

@Serializable
data class OrderData(
    val id: String,
    val symbol: String,
    val side: String, // "BUY" or "SELL"
    @SerialName("order_type")
    val orderType: String, // "MARKET", "LIMIT", "STOP", "STOP_LIMIT"
    val quantity: Double,
    val price: Double? = null,
    @SerialName("stop_price")
    val stopPrice: Double? = null,
    val status: String, // "PENDING", "OPEN", "FILLED", "PARTIALLY_FILLED", "CANCELLED", "REJECTED"
    @SerialName("filled_quantity")
    val filledQuantity: Double? = null,
    @SerialName("average_fill_price")
    val averageFillPrice: Double? = null,
    @SerialName("created_at")
    val createdAt: String? = null,
    @SerialName("updated_at")
    val updatedAt: String? = null,
)

/**
 * Real-time position update message.
 *
 * Sent when a position is opened, updated, or closed.
 */
@Serializable
@SerialName("position")
data class PositionMessage(
    override val timestamp: String,
    val data: PositionData,
) : WebSocketMessage()

@Serializable
data class PositionData(
    val id: String,
    val symbol: String,
    val quantity: Double,
    @SerialName("entry_price")
    val entryPrice: Double,
    @SerialName("current_price")
    val currentPrice: Double,
    @SerialName("unrealized_pnl")
    val unrealizedPnl: Double,
    @SerialName("unrealized_pnl_percent")
    val unrealizedPnlPercent: Double,
    @SerialName("realized_pnl")
    val realizedPnl: Double? = null,
    val side: String? = null, // "LONG" or "SHORT"
    @SerialName("opened_at")
    val openedAt: String? = null,
)

/**
 * Real-time market data message.
 *
 * Sent for market data updates (price ticks, order book changes, etc.)
 */
@Serializable
@SerialName("market_data")
data class MarketDataMessage(
    override val timestamp: String,
    val data: MarketData,
) : WebSocketMessage()

@Serializable
data class MarketData(
    val symbol: String,
    val bid: Double,
    val ask: Double,
    val last: Double,
    val volume: Double,
    val high: Double? = null,
    val low: Double? = null,
    val open: Double? = null,
    val close: Double? = null,
    @SerialName("bid_size")
    val bidSize: Double? = null,
    @SerialName("ask_size")
    val askSize: Double? = null,
    val change: Double? = null,
    @SerialName("change_percent")
    val changePercent: Double? = null,
)

/**
 * Heartbeat/ping message.
 *
 * Sent periodically by the backend to keep the connection alive.
 */
@Serializable
@SerialName("heartbeat")
data class HeartbeatMessage(
    override val timestamp: String,
    val status: String = "alive",
) : WebSocketMessage()

/**
 * Subscription confirmation message.
 *
 * Sent by the backend to confirm a channel subscription.
 */
@Serializable
@SerialName("subscription")
data class SubscriptionMessage(
    override val timestamp: String,
    val channel: String,
    val status: String, // "subscribed" or "unsubscribed"
    val message: String? = null,
) : WebSocketMessage()

/**
 * Error message from the backend.
 *
 * Sent when an error occurs (invalid subscription, authentication failure, etc.)
 */
@Serializable
@SerialName("error")
data class ErrorMessage(
    override val timestamp: String,
    val code: String,
    val message: String,
    val details: String? = null,
) : WebSocketMessage()
